### ISSUE TITLE
[Medical imaging] 3D-Unet build

### ISSUE THREAD

**Issue by lyly403** [ltechkorea/inference_results_v1.0#8]
1. Downloading dataset
`$MLPERF_SCRATCH_PATH/data/BraTS/MICCAI_BraTS_2019_Data_Training`

2. Preprocessing dataset
`python3 code/3d-unet/tensorrt/preprocess_data.py`

3. Downloading / obtaining the model
`bash code/3d-unet/tensorrt/download_model.sh`

4. `make build`

5. Generate TensorRT engines
`make generate_engines RUN_ARGS="--benchmarks=<BENCHMARKS> --scenarios=<SCENARIOS> --config_ver=default,high_accuracy [OTHER FLAGS]"`

6. Run inference through Loadgen
`make run RUN_ARGS="--benchmarks=3d-unet --scenarios=<SCENARIO> --config_ver=default --test_mode=PerformanceOnly"
`
`make run RUN_ARGS="--benchmarks=3d-unet --scenarios=<SCENARIO> --config_ver=default --test_mode=AccuracyOnly"`
`make run RUN_ARGS="--benchmarks=3d-unet --scenarios=<SCENARIO> --config_ver=high_accuracy --test_mode=PerformanceOnly"`
`make run RUN_ARGS="--benchmarks=3d-unet --scenarios=<SCENARIO> --config_ver=high_accuracy --test_mode=AccuracyOnly"`

**Comment by lyly403** [comment]
### 도커 안에서 실행 할 make 명령어
`make clone_loadgen`: 공식 MLPerf 추론 GitHub 리포지토리를 복제합니다.
`make build_plugins`: TensorRT 플러그인을 빌드합니다.
`make build_loadgen`: LoadGen 소스 코드를 빌드합니다.
`make build_harness`: 하네스를 만듭니다.
`make run RUN_ARGS="--benchmarks=<BENCHMARKS> --scenarios=<SCENARIOS> [OTHER RUN_ARGS FLAGS]"` 다음 단계를 실행합니다.
`make generate_engines RUN_ARGS="--benchmarks=<BENCHMARKS> --scenarios=<SCENARIOS> [OTHER RUN_ARGS FLAGS]"`: TensorRT에 최적화된 엔진 파일을 생성합니다.
`make run_harness RUN_ARGS="--benchmarks=<BENCHMARKS> --scenarios=<SCENARIOS> [OTHER RUN_ARGS FLAGS]"`: 엔진 파일 및 LoadGen으로 하네스를 실행합니다.

**Comment by lyly403** [comment]
### generate_engines 에러
(mlperf) sangwoo@mlperf-inference-sangwoo:/work$ make generate_engines RUN_ARGS="--benchmarks=3d-unet --scenarios=offline --config_ver=default"
[2021-07-20 13:31:54,610 __init__.py:255 INFO] Running command: CUDA_VISIBILE_ORDER=PCI_BUS_ID nvidia-smi --query-gpu=gpu_name,pci.device_id,uuid --format=csv
[2021-07-20 13:32:00,218 main.py:701 INFO] Detected System ID: V100S-PCIE-32GBx8
[2021-07-20 13:32:00,228 main.py:529 INFO] Using config files: configs/3d-unet/Offline/config.json
[2021-07-20 13:32:00,229 __init__.py:341 INFO] Parsing config file configs/3d-unet/Offline/config.json ...
[2021-07-20 13:32:00,230 main.py:542 INFO] Processing config "V100S-PCIE-32GBx8_3d-unet_Offline"
[2021-07-20 13:32:00,309 main.py:82 INFO] Building engines for 3d-unet benchmark in Offline scenario...
[2021-07-20 13:32:00,310 main.py:102 INFO] Building GPU engine for V100S-PCIE-32GBx8_3d-unet_Offline
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/work/code/main.py", line 108, in handle_generate_engine
    b.build_engines()
  File "/work/code/common/builder.py", line 142, in build_engines
    self.initialize()
  File "/work/code/3d-unet/tensorrt/3d-unet.py", line 292, in initialize
    model = self.preprocess_onnx(onnx.load(self.model_path))
  File "/usr/local/lib/python3.6/dist-packages/onnx/__init__.py", line 114, in load_model
    s = _load_bytes(f)
  File "/usr/local/lib/python3.6/dist-packages/onnx/__init__.py", line 30, in _load_bytes
    with open(cast(Text, f), 'rb') as readable:
FileNotFoundError: [Errno 2] No such file or directory: 'build/models/3d-unet/3dUNetBraTS.onnx'
Traceback (most recent call last):
  File "code/main.py", line 703, in <module>
    main(main_args, system)
  File "code/main.py", line 634, in main
    launch_handle_generate_engine(*_gen_args, **_gen_kwargs)
  File "code/main.py", line 62, in launch_handle_generate_engine
    raise RuntimeError("Building engines failed!")
RuntimeError: Building engines failed!
Makefile:599: recipe for target 'generate_engines' failed
make: *** [generate_engines] Error 1

**Comment by jay-huh** [comment]
# `3d-unet`

> `Offline`
> Accuracy: 99(`default`) and 99.9(`high_accuracy`)

## `Offline`
- [x] `default`
- [x] `high_accuracy`

## Command

```bash
  time docker run --gpus "device=6" --rm -t -w /work \
        -v /home/jay/work/inference-v1.0/closed/LTechKorea:/work -v /home/jay:/mnt//home/jay \
        --cap-add SYS_ADMIN --cap-add SYS_TIME \
        -e NVIDIA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
        --shm-size=32gb \
        -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro \
        --security-opt apparmor=unconfined --security-opt seccomp=unconfined \
        --name mlperf-inference-jay-1 -h mlperf-inference-jay --add-host mlperf-inference-jay:127.0.0.1 \
        --user 1001:1001 --net host --device /dev/fuse \
        -v /opt/data/scratch.mlperf_inference:/opt/data/scratch.mlperf_inference -v /opt/data/Dataset:/opt/data/Dataset  \
        -e MLPERF_SCRATCH_PATH=/opt/data/scratch.mlperf_inference \
        -e HOST_HOSTNAME=ltech-gpu10 \
        -e LD_LIBRARY_PATH=:/usr/local/cuda/lib64:/usr/lib/x86_64-linux-gnu:/home/jay/work/inference-v1.0/closed/LTechKorea/build/inference/loadgen/build:/usr/local/cuda-11.1/targets/x86_64-linux/lib/ \
         \
        mlperf-inference:jay make run_harness RUN_ARGS="--benchmarks=3d-unet --scenarios=Offline --config_ver=default,high_accuracy --test_mode=SubmissionRun --verbose --fast"

```

## Results

```
======================= Perf harness results: =======================

V100S-PCIE-32GBx1_TRT-default-Offline:
    3d-unet: result_samples_per_second: 9.74867, Result is VALID

V100S-PCIE-32GBx1_TRT-high_accuracy-Offline:
    3d-unet: result_samples_per_second: 9.72293, Result is VALID


======================= Accuracy results: =======================

V100S-PCIE-32GBx1_TRT-default-Offline:
    3d-unet: Accuracy = 0.853, Threshold = 0.844. Accuracy test PASSED.

V100S-PCIE-32GBx1_TRT-high_accuracy-Offline:
    3d-unet: Accuracy = 0.853, Threshold = 0.852. Accuracy test PASSED.

docker run --gpus "device=6" --rm -t -w /work -v  -v /home/jay:/mnt//home/jay  0.23s user 0.06s system 0% cpu 17:03.43 total

```
